# Generated by CMake, DO NOT EDIT
CMakeFiles/cmake.check_cache: \
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/CMakeCInformation.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/CMakeCXXInformation.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/CMakeCommonLanguageInclude.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/CMakeGenericSystem.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/CMakeParseArguments.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/CMakeSystemSpecificInformation.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/Compiler/GNU-C.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/Compiler/GNU-CXX.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/Compiler/GNU.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/FindCURL.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/FindOpenAL.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/FindOpenGL.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/FindPackageMessage.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/Platform/Darwin-GNU-C.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/Platform/Darwin-GNU-CXX.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/Platform/Darwin-GNU.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/Platform/Darwin.cmake\
/Applications/CMake\ 2.8-9.app/Contents/share/cmake-2.8/Modules/Platform/UnixPaths.cmake\
/Users/wangjiatc/Documents/MyProj/supertuxkart/CMakeFiles/CMakeCCompiler.cmake\
/Users/wangjiatc/Documents/MyProj/supertuxkart/CMakeFiles/CMakeCXXCompiler.cmake\
/Users/wangjiatc/Documents/MyProj/supertuxkart/CMakeFiles/CMakeSystem.cmake\
/Users/wangjiatc/Documents/MyProj/supertuxkart/CMakeLists.txt\
/Users/wangjiatc/Documents/MyProj/supertuxkart/cmake/BuildTypeSTKRelease.cmake\
/Users/wangjiatc/Documents/MyProj/supertuxkart/cmake/FindIrrlicht.cmake\
/Users/wangjiatc/Documents/MyProj/supertuxkart/cmake/FindOggVorbis.cmake\
/Users/wangjiatc/Documents/MyProj/supertuxkart/cmake/SourceGroupFunctions.cmake\
/Users/wangjiatc/Documents/MyProj/supertuxkart/data/supertuxkart_desktop.template\
/Users/wangjiatc/Documents/MyProj/supertuxkart/sources.cmake\
/Users/wangjiatc/Documents/MyProj/supertuxkart/src/bullet/CMakeLists.txt\
/Users/wangjiatc/Documents/MyProj/supertuxkart/src/enet/CMakeLists.txt\
/Users/wangjiatc/Documents/MyProj/supertuxkart/tools/font_tool/CMakeLists.txt
	/Applications/CMake\ 2.8-9.app/Contents/bin/cmake -H/Users/wangjiatc/Documents/MyProj/supertuxkart -B/Users/wangjiatc/Documents/MyProj/supertuxkart
